"""
PDF Generator - Converts markdown briefs to professionally styled PDFs.

Uses fpdf2 for pure Python PDF generation (no external dependencies).
"""

import re
from pathlib import Path
from datetime import datetime
from fpdf import FPDF
from fpdf.enums import XPos, YPos
from typing import Optional


# Color schemes for different brief types
COLORS = {
    "Sales": {
        "primary": (99, 102, 241),      # Indigo
        "secondary": (79, 70, 229),
        "accent": (238, 242, 255),
        "highlight": (129, 140, 248),
    },
    "Security": {
        "primary": (5, 150, 105),       # Green
        "secondary": (4, 120, 87),
        "accent": (236, 253, 245),
        "highlight": (16, 185, 129),
    },
    "Product": {
        "primary": (8, 145, 178),       # Cyan
        "secondary": (6, 116, 142),
        "accent": (236, 254, 255),
        "highlight": (34, 211, 238),
    },
}

# Confidence badge colors
CONFIDENCE_COLORS = {
    "HIGH": {"bg": (220, 252, 231), "text": (22, 101, 52), "label": "High Confidence"},
    "MEDIUM": {"bg": (254, 249, 195), "text": (133, 77, 14), "label": "Medium Confidence"},
    "LOW": {"bg": (254, 226, 226), "text": (153, 27, 27), "label": "Low Confidence"},
}

# Source tier badges
SOURCE_TIER_LABELS = {
    "TIER_0": {"label": "Official Source", "color": (22, 101, 52)},
    "TIER_1": {"label": "Verified", "color": (30, 64, 175)},
    "TIER_2": {"label": "Inferred", "color": (107, 114, 128)},
}


def sanitize_text(text: str) -> str:
    """Sanitize text for PDF output - replace problematic Unicode chars."""
    replacements = {
        '\u2014': '-',   # em-dash
        '\u2013': '-',   # en-dash
        '\u2018': "'",   # left single quote
        '\u2019': "'",   # right single quote
        '\u201c': '"',   # left double quote
        '\u201d': '"',   # right double quote
        '\u2026': '...', # ellipsis
        '\u00a0': ' ',   # non-breaking space
        '\u2022': '*',   # bullet
        '\u2023': '>',   # triangular bullet
        '\u25cf': '*',   # black circle
        '\u2192': '->',  # right arrow
        '\u2190': '<-',  # left arrow
        '\u2122': '(TM)', # trademark
        '\u00ae': '(R)',  # registered
        '\u00a9': '(C)',  # copyright
        # Source quality emoji indicators
        '\U0001F7E2': '[P]',  # green circle -> Primary
        '\U0001F7E1': '[S]',  # yellow circle -> Secondary
        '\U0001F534': '[W]',  # red circle -> Weak
        '\U0001F7E0': '[S]',  # orange circle -> Secondary
        '\u26AA': '[?]',      # white circle
        '\u2705': '[v]',      # check mark
        '\u274C': '[x]',      # cross mark
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text


class BriefPDF(FPDF):
    """Custom PDF class for Fluency briefs."""

    def __init__(self, brief_type: str = "Sales", company_name: str = "Company"):
        super().__init__()
        self.brief_type = brief_type
        self.company_name = sanitize_text(company_name)
        self.colors = COLORS.get(brief_type, COLORS["Sales"])

        # Set up fonts
        self.add_page()
        self.set_auto_page_break(auto=True, margin=25)

    def header(self):
        """Add header to each page."""
        if self.page_no() == 1:
            # First page header with colored banner
            self.set_fill_color(*self.colors["primary"])
            self.rect(0, 0, 210, 35, 'F')

            self.set_text_color(255, 255, 255)
            self.set_font("Helvetica", "B", 20)
            self.set_xy(15, 10)
            self.cell(0, 10, f"{self.company_name}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

            self.set_font("Helvetica", "", 11)
            self.set_xy(15, 22)
            self.cell(0, 6, f"{self.brief_type} Brief | Fluency AI Research", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

            self.set_text_color(0, 0, 0)
            self.ln(15)
        else:
            # Subsequent pages - simple header
            self.set_font("Helvetica", "I", 9)
            self.set_text_color(128, 128, 128)
            self.cell(0, 10, f"{self.company_name} - {self.brief_type} Brief", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            self.set_text_color(0, 0, 0)
            self.ln(5)

    def footer(self):
        """Add footer to each page."""
        self.set_y(-20)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)

        # Page number
        self.cell(0, 10, f"Page {self.page_no()}", align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Generation timestamp on first page
        if self.page_no() == 1:
            self.set_y(-15)
            self.set_font("Helvetica", "I", 7)
            timestamp = datetime.now().strftime("%B %d, %Y at %I:%M %p")
            self.cell(0, 5, f"Generated by Fluency AI Research Agent | {timestamp}", align="C")

        self.set_text_color(0, 0, 0)

    def section_header(self, text: str, level: int = 2):
        """Add a section header."""
        text = sanitize_text(text)
        self.ln(5)

        if level == 1:
            self.set_font("Helvetica", "B", 16)
            self.set_text_color(*self.colors["primary"])
        elif level == 2:
            self.set_font("Helvetica", "B", 13)
            self.set_text_color(31, 41, 55)
            # Add underline
            self.cell(0, 8, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            self.set_draw_color(229, 231, 235)
            self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
            self.ln(3)
            self.set_text_color(0, 0, 0)
            return
        elif level == 3:
            self.set_font("Helvetica", "B", 11)
            self.set_text_color(55, 65, 81)
        else:
            self.set_font("Helvetica", "B", 10)
            self.set_text_color(75, 85, 99)

        self.cell(0, 8, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def paragraph(self, text: str):
        """Add a paragraph of text."""
        self.set_font("Helvetica", "", 10)
        self.set_text_color(31, 41, 55)
        # Reset x position to left margin to ensure full width
        self.set_x(self.l_margin)
        self.multi_cell(0, 5, sanitize_text(text))
        self.ln(2)
        self.set_text_color(0, 0, 0)

    def bullet_point(self, text: str, indent: int = 0):
        """Add a bullet point."""
        self.set_font("Helvetica", "", 10)
        x = self.l_margin + (indent * 5)
        self.set_x(x)

        # Bullet character
        self.set_text_color(*self.colors["primary"])
        self.cell(5, 5, "*", new_x=XPos.RIGHT)

        # Text
        self.set_text_color(31, 41, 55)
        # Calculate remaining width
        remaining_width = self.w - self.r_margin - self.get_x()
        self.multi_cell(remaining_width, 5, sanitize_text(text))
        self.set_text_color(0, 0, 0)

    def quote_block(self, text: str, source: str = None):
        """Add a styled quote block."""
        self.ln(3)

        # Sanitize inputs
        text = sanitize_text(text)
        if source:
            source = sanitize_text(source)

        # Background
        start_y = self.get_y()
        self.set_fill_color(*self.colors["accent"])

        # Left border
        self.set_draw_color(*self.colors["primary"])
        self.set_line_width(1)

        # Quote text
        self.set_x(self.l_margin + 3)
        self.set_font("Helvetica", "I", 10)
        self.set_text_color(30, 64, 175)

        # Calculate height needed
        self.multi_cell(self.w - self.l_margin - self.r_margin - 6, 5, f'"{sanitize_text(text)}"')

        if source:
            self.set_font("Helvetica", "", 8)
            self.set_text_color(107, 114, 128)
            self.set_x(self.l_margin + 3)
            self.cell(0, 5, f"- {sanitize_text(source)}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        end_y = self.get_y()

        # Draw background and border
        self.set_fill_color(*self.colors["accent"])
        self.rect(self.l_margin, start_y - 2, self.w - self.l_margin - self.r_margin, end_y - start_y + 4, 'F')
        self.set_draw_color(*self.colors["primary"])
        self.line(self.l_margin, start_y - 2, self.l_margin, end_y + 2)

        # Rewrite text on top of background
        self.set_y(start_y)
        self.set_x(self.l_margin + 5)
        self.set_font("Helvetica", "I", 10)
        self.set_text_color(30, 64, 175)
        self.multi_cell(self.w - self.l_margin - self.r_margin - 10, 5, f'"{sanitize_text(text)}"')

        if source:
            self.set_font("Helvetica", "", 8)
            self.set_text_color(107, 114, 128)
            self.set_x(self.l_margin + 5)
            self.cell(0, 5, f"- {sanitize_text(source)}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        self.set_text_color(0, 0, 0)
        self.set_line_width(0.2)
        self.ln(5)

    def table_start(self, headers: list[str]):
        """Start a table with headers."""
        self.ln(3)
        col_width = (self.w - self.l_margin - self.r_margin) / len(headers)

        # Header row
        self.set_fill_color(243, 244, 246)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(55, 65, 81)

        for header in headers:
            self.cell(col_width, 8, sanitize_text(header), border=1, align="L", fill=True)
        self.ln()

        self.set_font("Helvetica", "", 9)
        self.set_text_color(0, 0, 0)
        self._table_col_width = col_width
        self._table_cols = len(headers)

    def table_row(self, cells: list[str]):
        """Add a row to the current table."""
        col_width = self._table_col_width

        # Alternate row colors
        if hasattr(self, '_row_count'):
            self._row_count += 1
        else:
            self._row_count = 0

        if self._row_count % 2 == 1:
            self.set_fill_color(249, 250, 251)
            fill = True
        else:
            fill = False

        for cell in cells:
            self.cell(col_width, 7, sanitize_text(str(cell))[:40], border=1, align="L", fill=fill)
        self.ln()

    def table_end(self):
        """End the current table."""
        self._row_count = 0
        self.ln(3)

    def score_display(self, label: str, score: int, max_score: int = 10):
        """Display a score with visual indicator."""
        self.set_font("Helvetica", "", 10)
        self.cell(80, 6, label)

        # Score value with color
        if score >= 7:
            self.set_text_color(5, 150, 105)  # Green
        elif score >= 4:
            self.set_text_color(217, 119, 6)  # Yellow
        else:
            self.set_text_color(220, 38, 38)  # Red

        self.set_font("Helvetica", "B", 10)
        self.cell(20, 6, f"{score}/{max_score}")

        # Visual bar
        self.set_draw_color(229, 231, 235)
        bar_x = self.get_x() + 5
        bar_y = self.get_y() + 2
        bar_width = 50
        bar_height = 4

        # Background bar
        self.set_fill_color(229, 231, 235)
        self.rect(bar_x, bar_y, bar_width, bar_height, 'F')

        # Filled portion
        if score >= 7:
            self.set_fill_color(5, 150, 105)
        elif score >= 4:
            self.set_fill_color(217, 119, 6)
        else:
            self.set_fill_color(220, 38, 38)

        fill_width = (score / max_score) * bar_width
        self.rect(bar_x, bar_y, fill_width, bar_height, 'F')

        self.set_text_color(0, 0, 0)
        self.ln(8)

    def confidence_badge(self, confidence: str, x: float = None, y: float = None):
        """Draw a confidence badge at the specified position."""
        if x is None:
            x = self.get_x()
        if y is None:
            y = self.get_y()

        conf_style = CONFIDENCE_COLORS.get(confidence, CONFIDENCE_COLORS["MEDIUM"])

        # Badge dimensions
        badge_width = 28
        badge_height = 5

        # Draw rounded badge background
        self.set_fill_color(*conf_style["bg"])
        self.set_draw_color(*conf_style["bg"])
        self.rect(x, y, badge_width, badge_height, 'F')

        # Badge text
        self.set_font("Helvetica", "B", 6)
        self.set_text_color(*conf_style["text"])
        self.set_xy(x, y + 0.5)
        self.cell(badge_width, badge_height - 1, conf_style["label"], align="C")

        self.set_text_color(0, 0, 0)
        return badge_width

    def source_tier_badge(self, tier: str, x: float = None, y: float = None):
        """Draw a source tier badge."""
        if x is None:
            x = self.get_x()
        if y is None:
            y = self.get_y()

        tier_style = SOURCE_TIER_LABELS.get(tier, SOURCE_TIER_LABELS["TIER_2"])

        # Badge text
        self.set_font("Helvetica", "I", 6)
        self.set_text_color(*tier_style["color"])
        self.set_xy(x, y)
        self.cell(25, 4, tier_style["label"])

        self.set_text_color(0, 0, 0)

    def score_gauge(self, score: int, label: str, x: float, y: float, width: float = 50):
        """Draw a circular-ish score gauge."""
        # Gauge background
        gauge_height = 8
        self.set_fill_color(229, 231, 235)
        self.rect(x, y, width, gauge_height, 'F')

        # Filled portion based on score
        if score >= 7:
            fill_color = (5, 150, 105)  # Green
        elif score >= 4:
            fill_color = (217, 119, 6)  # Amber
        else:
            fill_color = (220, 38, 38)  # Red

        self.set_fill_color(*fill_color)
        fill_width = (score / 10) * width
        self.rect(x, y, fill_width, gauge_height, 'F')

        # Score text overlay
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(255, 255, 255)
        self.set_xy(x + 2, y + 1)
        self.cell(width - 4, gauge_height - 2, f"{score}/10", align="L")

        # Label below
        self.set_font("Helvetica", "", 7)
        self.set_text_color(75, 85, 99)
        self.set_xy(x, y + gauge_height + 1)
        self.cell(width, 4, sanitize_text(label), align="C")

        self.set_text_color(0, 0, 0)

    def executive_summary_page(
        self,
        company_name: str,
        company_type: str,
        industry: str,
        description: str,
        scores: dict,
        opportunities: list,
        blockers: list,
        recommended_approach: str = ""
    ):
        """Generate an executive summary page."""
        # Company info section
        self.ln(8)
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(31, 41, 55)
        self.cell(0, 6, "Executive Summary", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_draw_color(*self.colors["primary"])
        self.set_line_width(0.5)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(5)

        # Company description box
        self.set_fill_color(*self.colors["accent"])
        start_y = self.get_y()
        self.set_font("Helvetica", "", 9)
        self.set_text_color(55, 65, 81)
        self.set_x(self.l_margin + 3)
        desc_text = sanitize_text(description[:300] + "..." if len(description) > 300 else description)
        self.multi_cell(self.w - self.l_margin - self.r_margin - 6, 4, desc_text)
        end_y = self.get_y()

        # Draw background
        self.set_fill_color(*self.colors["accent"])
        self.rect(self.l_margin, start_y - 2, self.w - self.l_margin - self.r_margin, end_y - start_y + 4, 'F')

        # Rewrite text
        self.set_y(start_y)
        self.set_x(self.l_margin + 3)
        self.set_text_color(55, 65, 81)
        self.multi_cell(self.w - self.l_margin - self.r_margin - 6, 4, desc_text)
        self.ln(5)

        # Company details row
        self.set_font("Helvetica", "", 8)
        self.set_text_color(107, 114, 128)
        details = f"Type: {company_type} | Industry: {industry}"
        self.cell(0, 4, sanitize_text(details), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.ln(5)

        # Deployment Readiness Scores Section
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(31, 41, 55)
        self.cell(0, 6, "Deployment Readiness Scores", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.ln(3)

        # Draw score gauges in a grid
        gauge_width = 55
        gauge_spacing = 60
        start_x = self.l_margin
        gauge_y = self.get_y()

        score_items = [
            ("security_maturity", "Security Maturity"),
            ("integration_fit", "Integration Fit"),
            ("compliance_complexity", "Compliance"),
        ]

        for i, (key, label) in enumerate(score_items):
            x = start_x + (i * gauge_spacing)
            score_val = scores.get(key, 5)
            self.score_gauge(score_val, label, x, gauge_y, gauge_width)

        self.set_y(gauge_y + 18)

        score_items_2 = [
            ("strategic_alignment", "Strategic Alignment"),
            ("deal_complexity", "Deal Complexity"),
            ("overall", "Overall Score"),
        ]

        gauge_y = self.get_y()
        for i, (key, label) in enumerate(score_items_2):
            x = start_x + (i * gauge_spacing)
            score_val = scores.get(key, 5)
            if isinstance(score_val, float):
                score_val = int(round(score_val))
            self.score_gauge(score_val, label, x, gauge_y, gauge_width)

        self.set_y(gauge_y + 22)

        # Two-column layout for opportunities and blockers
        col_width = (self.w - self.l_margin - self.r_margin - 10) / 2

        # Opportunities column
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(5, 150, 105)  # Green
        self.cell(col_width, 5, "Top Opportunities", new_x=XPos.RIGHT)

        # Blockers column header
        self.set_x(self.l_margin + col_width + 10)
        self.set_text_color(220, 38, 38)  # Red
        self.cell(col_width, 5, "Potential Blockers", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.ln(2)

        # Content rows
        max_items = max(len(opportunities[:3]), len(blockers[:3]))
        self.set_font("Helvetica", "", 8)

        for i in range(max_items):
            start_y = self.get_y()

            # Opportunity
            if i < len(opportunities):
                self.set_text_color(31, 41, 55)
                self.set_x(self.l_margin)
                opp_text = sanitize_text(opportunities[i][:80])
                self.multi_cell(col_width, 4, f"+ {opp_text}")

            opp_end_y = self.get_y()

            # Blocker
            if i < len(blockers):
                self.set_y(start_y)
                self.set_x(self.l_margin + col_width + 10)
                self.set_text_color(31, 41, 55)
                blocker_text = sanitize_text(blockers[i][:80])
                self.multi_cell(col_width, 4, f"- {blocker_text}")

            blocker_end_y = self.get_y()
            self.set_y(max(opp_end_y, blocker_end_y) + 1)

        self.ln(3)

        # Recommended approach
        if recommended_approach:
            self.set_font("Helvetica", "B", 9)
            self.set_text_color(*self.colors["primary"])
            self.cell(0, 5, "Recommended Approach", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            self.set_font("Helvetica", "", 8)
            self.set_text_color(55, 65, 81)
            approach_text = sanitize_text(recommended_approach[:200])
            self.multi_cell(0, 4, approach_text)

        self.set_text_color(0, 0, 0)
        self.ln(5)

    def add_claim_with_confidence(self, claim_text: str, confidence: str, source_tier: str = None):
        """Add a claim with confidence badge inline."""
        self.set_font("Helvetica", "", 9)
        self.set_text_color(31, 41, 55)

        # Calculate text width to position badge
        self.set_x(self.l_margin)

        # Draw bullet
        self.set_text_color(*self.colors["primary"])
        self.cell(5, 5, "*", new_x=XPos.RIGHT)

        # Draw claim text
        self.set_text_color(31, 41, 55)
        text = sanitize_text(claim_text[:100])
        self.cell(0, 5, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Add confidence badge on same line (right side)
        badge_x = self.w - self.r_margin - 30
        badge_y = self.get_y() - 5
        self.confidence_badge(confidence, badge_x, badge_y)

        # Source tier if provided
        if source_tier:
            self.source_tier_badge(source_tier, badge_x - 28, badge_y)

        self.set_text_color(0, 0, 0)


def parse_markdown_to_pdf(md_content: str, pdf: BriefPDF):
    """Parse markdown content and add to PDF."""
    lines = md_content.split('\n')
    i = 0
    in_table = False
    table_headers = []

    while i < len(lines):
        line = lines[i].strip()

        # Skip empty lines
        if not line:
            i += 1
            continue

        # Headers
        if line.startswith('# '):
            # Skip the main title (handled in header)
            i += 1
            continue
        elif line.startswith('## '):
            if in_table:
                pdf.table_end()
                in_table = False
            pdf.section_header(line[3:], 2)
        elif line.startswith('### '):
            if in_table:
                pdf.table_end()
                in_table = False
            pdf.section_header(line[4:], 3)
        elif line.startswith('#### '):
            if in_table:
                pdf.table_end()
                in_table = False
            pdf.section_header(line[5:], 4)

        # Blockquotes
        elif line.startswith('>'):
            if in_table:
                pdf.table_end()
                in_table = False

            quote_text = line[1:].strip()
            source = None

            # Check for source on next line
            if i + 1 < len(lines) and lines[i + 1].strip().startswith('>'):
                next_line = lines[i + 1].strip()[1:].strip()
                if next_line.startswith('—') or next_line.startswith('-'):
                    source = next_line.lstrip('—- ').strip()
                    i += 1

            pdf.quote_block(quote_text, source)

        # Tables
        elif line.startswith('|'):
            cells = [c.strip() for c in line.split('|')[1:-1]]

            # Check if this is a separator line
            if all(c.replace('-', '').replace(':', '') == '' for c in cells):
                i += 1
                continue

            if not in_table:
                # This is a header row
                table_headers = cells
                pdf.table_start(cells)
                in_table = True
            else:
                # Data row
                pdf.table_row(cells)

        # Bullet points
        elif line.startswith('- ') or line.startswith('* '):
            if in_table:
                pdf.table_end()
                in_table = False
            text = line[2:].strip()
            # Clean up markdown formatting
            text = re.sub(r'\*\*([^*]+)\*\*', r'\1', text)  # Bold
            text = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', text)  # Links
            pdf.bullet_point(text)

        # Numbered lists
        elif re.match(r'^\d+\.\s', line):
            if in_table:
                pdf.table_end()
                in_table = False
            text = re.sub(r'^\d+\.\s*', '', line)
            text = re.sub(r'\*\*([^*]+)\*\*', r'\1', text)
            text = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', text)
            pdf.bullet_point(text)

        # Horizontal rules
        elif line.startswith('---') or line.startswith('***'):
            if in_table:
                pdf.table_end()
                in_table = False
            pdf.ln(5)

        # Bold text line (like **Rationale:**)
        elif line.startswith('**') and line.endswith('**'):
            if in_table:
                pdf.table_end()
                in_table = False
            text = sanitize_text(line.strip('*'))
            pdf.set_font("Helvetica", "B", 10)
            pdf.multi_cell(0, 5, text)
            pdf.set_font("Helvetica", "", 10)

        # Regular paragraph
        elif not line.startswith('*Generated'):
            if in_table:
                pdf.table_end()
                in_table = False
            # Clean up markdown
            text = re.sub(r'\*\*([^*]+)\*\*', r'\1', line)
            text = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', text)
            if text:
                pdf.paragraph(text)

        i += 1

    if in_table:
        pdf.table_end()


def generate_pdf(
    md_content: str,
    output_path: str,
    title: str,
    brief_type: str = "Sales",
    synthesis_data: Optional[dict] = None,
    profile_data: Optional[dict] = None
) -> bool:
    """
    Generate a PDF from markdown content.

    Args:
        md_content: Markdown content
        output_path: Path to save the PDF
        title: Document title (used to extract company name)
        brief_type: Type of brief (Sales, Security, Product)
        synthesis_data: Optional synthesis data for executive summary
        profile_data: Optional company profile data

    Returns:
        True if successful, False otherwise
    """
    try:
        # Extract company name from title
        company_name = title.replace(f" - {brief_type} Brief", "").strip()

        # Create PDF
        pdf = BriefPDF(brief_type=brief_type, company_name=company_name)

        # Add executive summary if synthesis data provided
        if synthesis_data and profile_data:
            scores = synthesis_data.get("deployment_score", {})
            pdf.executive_summary_page(
                company_name=company_name,
                company_type=profile_data.get("company_type", "Unknown"),
                industry=profile_data.get("industry", "Unknown"),
                description=profile_data.get("description", ""),
                scores=scores,
                opportunities=synthesis_data.get("opportunities", []),
                blockers=synthesis_data.get("blockers", []),
                recommended_approach=synthesis_data.get("recommended_approach", "")
            )

            # Add a page break after executive summary
            pdf.add_page()

        # Parse and add content
        parse_markdown_to_pdf(md_content, pdf)

        # Save PDF
        pdf.output(output_path)

        return True
    except Exception as e:
        print(f"Error generating PDF: {e}")
        import traceback
        traceback.print_exc()
        return False


def generate_all_pdfs(
    output_dir: Path,
    company_name: str,
    sales_brief: str,
    security_brief: str,
    product_brief: str,
    synthesis_data: Optional[dict] = None,
    profile_data: Optional[dict] = None
) -> dict[str, str]:
    """
    Generate all PDF briefs for a company.

    Args:
        output_dir: Directory to save PDFs
        company_name: Company name for titles
        sales_brief: Sales brief markdown
        security_brief: Security brief markdown
        product_brief: Product brief markdown
        synthesis_data: Optional synthesis output for executive summary
        profile_data: Optional company profile data

    Returns:
        Dictionary of brief type to PDF path
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    pdfs = {}

    briefs = [
        ("Sales", sales_brief, "sales_brief.pdf"),
        ("Security", security_brief, "security_brief.pdf"),
        ("Product", product_brief, "product_brief.pdf"),
    ]

    for brief_type, content, filename in briefs:
        pdf_path = output_dir / filename
        title = f"{company_name} - {brief_type} Brief"

        if generate_pdf(
            content,
            str(pdf_path),
            title,
            brief_type,
            synthesis_data=synthesis_data,
            profile_data=profile_data
        ):
            pdfs[brief_type.lower()] = str(pdf_path)

    return pdfs
